### ISSUE TITLE
Bug report: the code does not work in NodeJS engine v0.4

### ISSUE THREAD

**Issue by jozefizso** [inspect-js/deep-equal-json#2]
I am running on Ubuntu 14.04 LTS with node v0.4.12 and npm v1.0.106.

I want to use the `deep-equal-json` package, install dependencies and run tests. Unfortunately the package does not work.

Expected behavior: The packages work on the engine v0.4 as described in the `package.json` file.

Actual behavior:

```
jozef@nodejsv4:~/deep-equal-json$ git log -n1
commit 56c2cf7a6af4eca850121186e4667880a336d858
Author: Jordan Harband <ljharb@gmail.com>
Date:   Mon Jun 5 22:31:26 2023 -0700

    v1.0.0
jozef@nodejsv4:~/deep-equal-json$ node -v
v0.4.12
jozef@nodejsv4:~/deep-equal-json$ npm -v
1.0.106
jozef@nodejsv4:~/deep-equal-json$ npm install
npm ERR! Error: No compatible version found: isarray@'^2.0.5'
npm ERR! Valid install targets:
npm ERR! ["0.0.0","0.0.1","1.0.0","2.0.0","2.0.1","2.0.2","2.0.3","2.0.4","2.0.5"]
npm ERR!     at installTargetsError (/home/jozef/npm-cli/lib/cache.js:424:10)
npm ERR!     at /home/jozef/npm-cli/lib/cache.js:371:15
npm ERR!     at saved (/home/jozef/npm-cli/lib/utils/npm-registry-client/get.js:136:7)
npm ERR!     at cb (/home/jozef/npm-cli/node_modules/graceful-fs/graceful-fs.js:36:9)
npm ERR! Report this *entire* log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR!
npm ERR! System Linux 4.4.0-148-generic
npm ERR! command "node" "/home/jozef/.nvm/v0.4.12/bin/npm" "install"
npm ERR! cwd /home/jozef/deep-equal-json
npm ERR! node -v v0.4.12
npm ERR! npm -v 1.0.106
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jozef/deep-equal-json/npm-debug.log
npm not ok
jozef@nodejsv4:~/deep-equal-json$ npm test

> deep-equal-json@1.0.0 pretest /home/jozef/deep-equal-json
> npm run lint


> deep-equal-json@1.0.0 lint /home/jozef/deep-equal-json
> eslint --ext=js,mjs .

sh: 1: eslint: not found
npm ERR! deep-equal-json@1.0.0 lint: `eslint --ext=js,mjs .`
npm ERR! `sh "-c" "eslint --ext=js,mjs ."` failed with 127
npm ERR!
npm ERR! Failed at the deep-equal-json@1.0.0 lint script.
npm ERR! This is most likely a problem with the deep-equal-json package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint --ext=js,mjs .
npm ERR! You can get their info via:
npm ERR!     npm owner ls deep-equal-json
npm ERR! There is likely additional logging output above.
npm ERR!
npm ERR! System Linux 4.4.0-148-generic
npm ERR! command "node" "/home/jozef/.nvm/v0.4.12/bin/npm" "run" "lint"
npm ERR! cwd /home/jozef/deep-equal-json
npm ERR! node -v v0.4.12
npm ERR! npm -v 1.0.106
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jozef/deep-equal-json/npm-debug.log
npm not ok
npm ERR! deep-equal-json@1.0.0 pretest: `npm run lint`
npm ERR! `sh "-c" "npm run lint"` failed with 1
npm ERR!
npm ERR! Failed at the deep-equal-json@1.0.0 pretest script.
npm ERR! This is most likely a problem with the deep-equal-json package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint
npm ERR! You can get their info via:
npm ERR!     npm owner ls deep-equal-json
npm ERR! There is likely additional logging output above.
npm ERR!
npm ERR! System Linux 4.4.0-148-generic
npm ERR! command "node" "/home/jozef/.nvm/v0.4.12/bin/npm" "test"
npm ERR! cwd /home/jozef/deep-equal-json
npm ERR! node -v v0.4.12
npm ERR! npm -v 1.0.106
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jozef/deep-equal-json/npm-debug.log
npm not ok
```

**Comment by ljharb** [comment]
Your install failed. That's an issue with npm, not with this package.

If you're using nvm, you can `nvm install-latest-npm` and you may be able to install packages, but once the package is installed, it'll work on node 0.4 just fine.

Separately, I'm not sure why you're pigeonholing on this particular thing - if I marked it as `>= 0.8`, would all of your concerns vanish?

**Comment by jozefizso** [comment]
You stated numerous times you support v0.4 in your packages.

This report shows it does not work as promised.

**Comment by ljharb** [comment]
It does. You’re responsible for installing it first before this package comes into play.
